name: log_export
description: "Save the log as a file."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  synchronized: ^3.1.0
  timezone: ^0.9.2
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: org.lulzm.log_export
        pluginClass: LogExportPlugin
      ios:
        pluginClass: LogExportPlugin
      linux:
        pluginClass: LogExportPlugin
      macos:
        pluginClass: LogExportPlugin
      windows:
        pluginClass: LogExportPluginCApi